name: Godot Android Export

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Godot
        uses: firebelley/setup-godot@v2
        with:
          version: "4.3"
          export-templates: true

      - name: Export Android APK
        run: |
          mkdir -p build/android
          godot --headless --export-release "Android" build/android/my-game.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/android/my-game.apk
