name: Godot Android Export

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Godot Android Export
        uses: firebelley/godot-export@v5.2.0
        with:
          version: 4.1.1
          export-type: Android
          export-path: build/my-game.apk
