name: Godot Android Export

on:
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up Godot
      - name: Set up Godot
        uses: firebelley/setup-godot@v1.1.0
        with:
          version: 4.2.1
          mono: false

      # Export Android APK
      - name: Export APK
        run: |
          mkdir -p build
          godot --headless --export-release "Android" build/my-horror-game.apk

      # Upload APK to GitHub Actions artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-horror-game
          path: build/my-horror-game.apk
